"""Initial migration

Revision ID: 844a81fbd4c0
Revises: 
Create Date: 2025-05-20 07:33:13.865075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844a81fbd4c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('notifications_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_type', sa.String(length=100), nullable=False),
    sa.Column('practitioner_name', sa.String(length=100), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('starting_time', sa.Time(), nullable=False),
    sa.Column('ending_time', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('provider_number', sa.Integer(), nullable=True),
    sa.Column('appointment_type', sa.String(length=100), nullable=False),
    sa.Column('appointment_notes', sa.String(length=1000), nullable=False),
    sa.Column('reminder', sa.Text(), nullable=True),
    sa.Column('custom_reminder', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=200), nullable=False),
    sa.Column('document_name', sa.String(length=100), nullable=False),
    sa.Column('upload_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_notes', sa.String(length=1000), nullable=False),
    sa.Column('practitioner_name', sa.String(length=100), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('practitioner_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('insurance_type', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_documents')
    op.drop_table('user_profile')
    op.drop_table('documents')
    op.drop_table('appointments')
    op.drop_table('user')
    # ### end Alembic commands ###
